name: Build Med_static for Windows and macOS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install pyinstaller
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build app
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            pyinstaller --onefile --noconsole --icon=icons/app.ico --add-data "data;data" Med_static.py
          else
            pyinstaller --windowed --onefile --icon=icons/app.icns --add-data "data:data" Med_static.py
          fi

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Med_static-${{ runner.os }}
          path: dist/
